events {
  worker_connections 1024;
}

http {
  log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                  '$status $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" "$http_x_forwarded_for"';

  error_log /var/log/nginx/error.file.log warn;
  access_log /var/log/nginx/access.file.log main;

  server {
    listen 80;
    server_name logs.staging.csds.qld.edu.au;

    location / {
      proxy_pass http://127.0.0.1:9000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }

  server {
    listen 80;
    server_name stats.staging.csds.qld.edu.au;

    location / {
      proxy_pass http://127.0.0.1:9090;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }

  server {
    listen 127.0.0.1:9080;

    location /nginx_status {
      stub_status;
      allow 127.0.0.1;
      deny all;
    }
  }
  
  server {
    listen 80 default_server;
    #listen 443 ssl;
    #ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    #ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
    #location /.well-known/acme-challenge/ {
    #  root /var/www/certbot;
    #}

    server_name 15.134.179.192;
    location / {
      return 200 'nginx is running\n';
      add_header Content-Type text/plain;
    }
  }
}
